#pragma once

enum class MessageIDs
{
    ANY,
    STATE,
    GLOBAL_POSITION,
    LOCAL_POSITION,
    GLOBAL_HOME,
    LOCAL_VELOCITY,
    CONNECTION_CLOSED,
    RAW_GYROSCOPE,
    RAW_ACCELEROMETER,
    BAROMETER,
    DISTANCE_SENSOR,
    ATTITUDE,
    GPS_INPUT_SENSOR,
    RAW_IMU_SENSOR
};
